### ISSUE TITLE
Java chat examples

### ISSUE THREAD

**Issue by andreapregno97** [realtho/SOAsec-Chat#4]
# Esempio di riferimento - GUI chat di gruppo con possibilità di creare conversazioni private:
https://digilander.libero.it/Java_example/

#### Altro esempio (solo chat di gruppo):
https://www.mrwebmaster.it/java/semplice-chat-java_7548.html

**Comment by davideolgiati** [comment]
Ho letto i due esempi linkati e secondo me potremmo orientarla in 2 direzioni differenti

1) chat user-to-user, io mi collego al mio server vedo gli utenti collegati e comincio a parlarci
2) chat stile [irc](https://it.m.wikipedia.org/wiki/Internet_Relay_Chat), mi collego al server e cerco un "canale" su cui parlare

nel primo caso possiamo optare per l'utilizzo del certificato X.509 per identificare la veridicità dell'utente e del server
nel secondo caso possiamo implementare le policy (chi può accedere, chi può scrivere, chi può creare canali, chi può invitare...)

la seconda opzione richiederebbe uno storico dei messaggi e una chiave simmetrica statica. Potrebbe anche essere crittografata e risiedere sul server, ma l'amministratore del canale dovrebbe decriptarla e rinviarla al server criptata con la chiave publica del nuovo partecipante a ogni aggiunta. il server dovrebbe tenere una lista di chiavi per ogni canale, comunque fattibile
