### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by andreapregno97** [realtho/SOAsec-Chat#5]
* WS-Policy: capire quali policy poter applicare e come implementarle.
* WS Secure Conversation:
cos'è e come funziona?
è possibile applicarlo alla chat?
come implementarlo?

**Comment by davideolgiati** [comment]
Ho fatto un pò di ricerche, ma a me sembra un passo indietro rispetto a WS-Security. Guarda cosa dice nella parte _performance_ in questo articolo: 
https://en.wikipedia.org/wiki/WS-Security
Sembra che si abbandona X.509 con questo metodo 

Comunque riguardo le implicazioni di questo meccanismo ho trovato questi due articoli:
https://en.wikipedia.org/wiki/WS-SecureConversation

> Following a pattern similar to TLS, WS-SecureConversation establishes a kind of session key. The processing overhead for key establishment is reduced significantly when compared to WS-Security in the case of frequent message exchanges. However, a new layer is put on top of WS-Security, that implies other WS-* protocols like WS-Addressing and WS-Trust. So the importance of performance has to be compared to the added complexity and dependencies. See the performance section in WS-Security.

https://www.ibm.com/support/knowledgecenter/SSEQTP_8.5.5/com.ibm.websphere.base.doc/ae/cwbs_establishsct_sc.html

> After the security context token is established, the application messages are secured with message protection by using keys that are derived from the secret of the security context token. The derived keys are used to secure the application messages by signing and encrypting the application messages. The security context token contains a UUID, which is used as identification of a shared secret. The token UUID can be used in the SOAP message to identify the security context token for the message exchanges. The secret must be kept in memory by the session participants (in this case the initiator and the recipient) and protected. Compromising the secret undermines the secure conversation between the participants.

In sintesi Secure conversation, se non ho capito male, utilizza un token di sessione condiviso tra client e server per autenticare che non ci sia stata manomissione

**Comment by davideolgiati** [comment]
Per WS-Policy ci sto ancora ragionando, dopo butto giù uno schemino e lo pubblico qui
